export const SELECT_ORG                    = 'SELECT_ORG'
export const FETCH_ORG_REQUEST             = 'FETCH_ORG_REQUEST'
export const FETCH_ORG_SUCCESS             = 'FETCH_ORG_SUCCESS'
export const FETCH_ORG_FAILURE             = 'FETCH_ORG_FAILURE'

export const FETCH_ORGS_REQUEST            = 'FETCH_ORGS_REQUEST'
export const FETCH_ORGS_SUCCESS            = 'FETCH_ORGS_SUCCESS'
export const FETCH_ORGS_FAILURE            = 'FETCH_ORGS_FAILURE'

export const FETCH_MEMBERS_REQUEST         = 'FETCH_MEMBERS_REQUEST'
export const FETCH_MEMBERS_SUCCESS         = 'FETCH_MEMBERS_SUCCESS'
export const FETCH_MEMBERS_FAILURE         = 'FETCH_MEMBERS_FAILURE'

export const FETCH_DEVICE_REQUEST          = 'FETCH_DEVICE_REQUEST'
export const FETCH_DEVICE_SUCCESS          = 'FETCH_DEVICE_SUCCESS'
export const FETCH_DEVICE_FAILURE          = 'FETCH_DEVICE_FAILURE'

export const FETCH_DEVICES_REQUEST         = 'FETCH_DEVICES_REQUEST'
export const FETCH_DEVICES_SUCCESS         = 'FETCH_DEVICES_SUCCESS'
export const FETCH_DEVICES_FAILURE         = 'FETCH_DEVICES_FAILURE'

export const FETCH_OCTOBLU_USER_REQUEST    = 'FETCH_OCTOBLU_USER_REQUEST'
export const FETCH_OCTOBLU_USER_SUCCESS    = 'FETCH_OCTOBLU_USER_SUCCESS'
export const FETCH_OCTOBLU_USER_FAILURE    = 'FETCH_OCTOBLU_USER_FAILURE'

export const FETCH_TEAMS_REQUEST           = 'FETCH_TEAMS_REQUEST'
export const FETCH_TEAMS_SUCCESS           = 'FETCH_TEAMS_SUCCESS'
export const FETCH_TEAMS_FAILURE           = 'FETCH_TEAMS_FAILURE'

export const FETCH_TEAM_SUCCESS            = 'FETCH_TEAM_SUCCESS'
export const FETCH_TEAM_FAILURE            = 'FETCH_TEAM_FAILURE'

export const FETCH_TEAM_MEMBERS_REQUEST    = 'FETCH_TEAM_MEMBERS_REQUEST'
export const FETCH_TEAM_MEMBERS_SUCCESS    = 'FETCH_TEAM_MEMBERS_SUCCESS'
export const FETCH_TEAM_MEMBERS_FAILURE    = 'FETCH_TEAM_MEMBERS_FAILURE'

export const LINK_MEMBER_TO_USER_REQUEST   = 'LINK_MEMBER_TO_USER_REQUEST'
export const LINK_MEMBER_TO_USER_SUCCESS   = 'LINK_MEMBER_TO_USER_SUCCESS'
export const LINK_MEMBER_TO_USER_FAILURE   = 'LINK_MEMBER_TO_USER_FAILURE'

export const MEMBER_ADD                    = 'MEMBER_ADD'
export const MEMBER_REMOVE                 = 'MEMBER_REMOVE'

export const ADD_DEVICE_REQUEST            = 'ADD_DEVICE_REQUEST'
export const ADD_DEVICE_SUCCESS            = 'ADD_DEVICE_SUCCESS'
export const ADD_DEVICE_FAILURE            = 'ADD_DEVICE_FAILURE'

export const DELETE_DEVICE_REQUEST         = 'DELETE_DEVICE_REQUEST'
export const DELETE_DEVICE_SUCCESS         = 'DELETE_DEVICE_SUCCESS'
export const DELETE_DEVICE_FAILURE         = 'DELETE_DEVICE_FAILURE'

export const FETCH_DEVICE_TOKEN_REQUEST    = 'FETCH_DEVICE_TOKEN_REQUEST'
export const FETCH_DEVICE_TOKEN_SUCCESS    = 'FETCH_DEVICE_TOKEN_SUCCESS'
export const FETCH_DEVICE_TOKEN_FAILURE    = 'FETCH_DEVICE_TOKEN_FAILURE'

export const UPDATE_DEVICE_REQUEST         = 'UPDATE_DEVICE_REQUEST'
export const UPDATE_DEVICE_SUCCESS         = 'UPDATE_DEVICE_SUCCESS'
export const UPDATE_DEVICE_FAILURE         = 'UPDATE_DEVICE_FAILURE'

export const NULLIFY_SELECTED_DEVICE       = 'NULLIFY_SELECTED_DEVICE'
export const NULLIFY_SELECTED_DEVICE_TOKEN = 'NULLIFY_SELECTED_DEVICE_TOKEN'

export const LOGOUT_USER                   = 'LOGOUT_USER'

export const STORE_AUTHENTICATION          = 'STORE_AUTHENTICATION'

export const INVITE_MEMBERS_REQUEST        = 'INVITE_MEMBERS_REQUEST'
export const INVITE_MEMBERS_SUCCESS        = 'INVITE_MEMBERS_SUCCESS'
export const INVITE_MEMBERS_FAILURE        = 'INVITE_MEMBERS_FAILURE'

export const DELETE_MEMBER_REQUEST         = 'DELETE_MEMBER_REQUEST'
export const DELETE_MEMBER_SUCCESS         = 'DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAILURE         = 'DELETE_MEMBER_FAILURE'
